import os, sys, shutil, datetime



class Manipulations():

    def __init__(self):
        test = 1



    def dublicateCase(self, baseCasePath='', newPath='', mode=''):
        """The function creates copy of the base case.
           pathBaseCase is the path of base case that will be copied by the function
           pathNewCase is the path of new case that will be created by the function
           mode defines how the procedure of copying will be done.
                   a) rewrite mode is the mode when folder of new case already being existed, then the folder
                   will delited by the function and base case folder will be copied to the folder being the same name
                   b) copy mode is the mode when folder of new case already being existed, then the folder will be copied
                   to the folder being old name with prefix of current time of copying. And new case will be copied
                    to folder being path of pathNewCase variables."""

        self.checkExistence(baseCasePath, newPath)

        if mode == 'rewrite':
                print(f'The folder {os.path.basename(newPath)}  is exist. The script run the rewrite mode')
                shutil.rmtree(newPath)
                shutil.copytree(baseCasePath, newPath)
        elif mode == 'copy':
                print(f'The folder {os.path.basename(newPath)}  is exist. The script run the copy mode')
                now = datetime.datetime.now()
                old_file = newPath + '_' + 'old' + '_' + now.strftime("%d-%m-%Y %H:%M")
                try:
                    shutil.move(newPath, old_file)
                    self.oldNameCase = os.path.basename(old_file)
                except shutil.Error:
                    print('You run the script is often. There is exception old case')
                shutil.copytree(baseCasePath, newPath)
        else:
                shutil.copytree(baseCasePath, newPath)

        self.baseCasePath = baseCasePath
        self.newPath = newPath
        self.newNameCase = os.path.basename(newPath)


    def generatorNewNameFolder(self, *namesNewCase, baseNewCase='', splitter='_'):
        """The function serves to create two variables of base and new case paths.
        The name of new case is generated by special algorithm realized in the fucntion.
        The name will be created by adding variables of the list namesNewCase to base case folder name. The variables
        will be seprated by special sympol (spliter) to name of the folder.
         Variables:
                    *namesNewCase is a number of variables, which will be added to name of new case
                    baseCase is the folder name of base case
                    splitter is the variables defending the for separation in folder name of new case """
        for addName in namesNewCase:
            baseNewCase += splitter + str(addName)

        self.newNameCase = baseNewCase
        return self.newNameCase

    def createNewPath(self, dirmame=None, newCaseName=None):
        """The function is used for creating new path
        Variables
        dirname is the path of directory where new folder of case put
        newCaseName is the name of new case

        newPath is the path of new case
        """
        self.newPath = os.path.join(dirmame, newCaseName)




    def checkExistence(self, baseCasePath, newPath):
        if not os.path.exists(baseCasePath):
            sys.exit('Error: The base case is not exist in the directory!!!')
        elif not os.path.exists(newPath):
            dirname, newCaseName = os.path.split(newPath)
            if os.path.exists(dirname):
                os.mkdir(f'{newCaseName}')
            else:
                sys.exit(f'Error: The new path {dirname} is not exist !!!')


